import type {
  ChangeInitiative,
  PulseSurvey,
  LeaderboardEntry,
  Nudge,
} from '@changeforge/shared';

export const MOCK_INITIATIVES: ChangeInitiative[] = [
  {
    id: 'init-001',
    name: 'Migração para Microsoft 365',
    description:
      'Migração completa do ecossistema de produtividade da empresa para Microsoft 365, incluindo Teams, SharePoint e OneDrive.',
    status: 'active',
    riskLevel: 'high',
    startDate: '2026-03-01',
    endDate: '2026-08-31',
    ownerId: 'user-admin-001',
    departments: ['TI', 'Vendas', 'RH', 'Financeiro'],
    technologies: ['Microsoft Teams', 'SharePoint', 'OneDrive', 'Outlook'],
    adkarScores: {
      awareness: 80,
      desire: 62,
      knowledge: 55,
      ability: 48,
      reinforcement: 35,
    },
    adoptionRate: 67,
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-05-28T15:00:00Z',
  },
  {
    id: 'init-002',
    name: 'Implantação Salesforce CRM',
    description:
      'Implementação do Salesforce Sales Cloud para o time de vendas, substituindo planilhas e sistemas legados.',
    status: 'active',
    riskLevel: 'critical',
    startDate: '2026-04-01',
    endDate: '2026-09-30',
    ownerId: 'user-admin-001',
    departments: ['Vendas', 'Marketing'],
    technologies: ['Salesforce Sales Cloud', 'Salesforce Marketing Cloud'],
    adkarScores: {
      awareness: 72,
      desire: 44,
      knowledge: 50,
      ability: 38,
      reinforcement: 22,
    },
    adoptionRate: 42,
    createdAt: '2026-03-20T10:00:00Z',
    updatedAt: '2026-05-28T15:00:00Z',
  },
  {
    id: 'init-003',
    name: 'Novo ERP – SAP S/4HANA',
    description:
      'Substituição do sistema legado de gestão por SAP S/4HANA, impactando finanças, compras e logística.',
    status: 'active',
    riskLevel: 'critical',
    startDate: '2026-01-15',
    endDate: '2026-12-31',
    ownerId: 'user-admin-002',
    departments: ['Financeiro', 'Operações', 'Compras'],
    technologies: ['SAP S/4HANA', 'SAP Fiori'],
    adkarScores: {
      awareness: 65,
      desire: 38,
      knowledge: 42,
      ability: 30,
      reinforcement: 18,
    },
    adoptionRate: 35,
    createdAt: '2026-01-05T10:00:00Z',
    updatedAt: '2026-05-28T15:00:00Z',
  },
  {
    id: 'init-004',
    name: 'Cultura de Dados – Power BI',
    description:
      'Disseminação de uma cultura data-driven com Power BI para todos os gestores e líderes da organização.',
    status: 'active',
    riskLevel: 'medium',
    startDate: '2026-05-01',
    endDate: '2026-10-31',
    ownerId: 'user-admin-003',
    departments: ['TI', 'RH', 'Financeiro', 'Operações'],
    technologies: ['Power BI', 'Azure Data Lake'],
    adkarScores: {
      awareness: 90,
      desire: 75,
      knowledge: 68,
      ability: 60,
      reinforcement: 50,
    },
    adoptionRate: 78,
    createdAt: '2026-04-15T10:00:00Z',
    updatedAt: '2026-05-28T15:00:00Z',
  },
  {
    id: 'init-005',
    name: 'Agile Transformation',
    description:
      'Transformação ágil com framework SAFe para 12 squads de produto, mudando cultura e processos de desenvolvimento.',
    status: 'paused',
    riskLevel: 'high',
    startDate: '2026-02-01',
    endDate: '2026-07-31',
    ownerId: 'user-admin-002',
    departments: ['TI', 'Produto'],
    technologies: ['Jira', 'Confluence', 'Miro'],
    adkarScores: {
      awareness: 85,
      desire: 55,
      knowledge: 70,
      ability: 65,
      reinforcement: 48,
    },
    adoptionRate: 58,
    createdAt: '2026-01-25T10:00:00Z',
    updatedAt: '2026-05-10T09:00:00Z',
  },
  {
    id: 'init-006',
    name: 'Onboarding Digital RH',
    description:
      'Digitalização do processo de onboarding de colaboradores com plataforma de LMS e jornada automatizada.',
    status: 'completed',
    riskLevel: 'low',
    startDate: '2025-11-01',
    endDate: '2026-03-31',
    ownerId: 'user-admin-003',
    departments: ['RH'],
    technologies: ['LMS Moodle', 'DocuSign', 'Slack'],
    adkarScores: {
      awareness: 95,
      desire: 88,
      knowledge: 92,
      ability: 85,
      reinforcement: 80,
    },
    adoptionRate: 94,
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
  },
];

export const MOCK_SURVEYS: PulseSurvey[] = [
  {
    id: 'survey-001',
    initiativeId: 'init-001',
    title: 'Pulse Check – Microsoft 365 · Semana 12',
    questions: [
      {
        id: 'q1',
        text: 'Você se sente confortável usando o Microsoft Teams?',
        type: 'likert',
        adkarStage: 'ability',
      },
      {
        id: 'q2',
        text: 'Com que frequência você utiliza o Teams para reuniões?',
        type: 'multiple_choice',
        options: ['Nunca', '1–2x/semana', '3–4x/semana', 'Diariamente'],
        adkarStage: 'ability',
      },
      {
        id: 'q3',
        text: 'O que mais dificulta sua adoção do M365?',
        type: 'open_text',
        adkarStage: 'knowledge',
      },
    ],
    targetDepartments: ['TI', 'Vendas'],
    scheduledAt: '2026-05-20T09:00:00Z',
    responseRate: 78,
    createdAt: '2026-05-15T08:00:00Z',
  },
  {
    id: 'survey-002',
    initiativeId: 'init-002',
    title: 'Salesforce – Barreiras de Adoção',
    questions: [
      {
        id: 'q1',
        text: 'Você entende o motivo desta mudança para o Salesforce?',
        type: 'likert',
        adkarStage: 'awareness',
      },
      {
        id: 'q2',
        text: 'Como você avalia seu nível de treinamento?',
        type: 'nps',
        adkarStage: 'knowledge',
      },
    ],
    targetDepartments: ['Vendas', 'Marketing'],
    responseRate: 61,
    createdAt: '2026-05-22T10:00:00Z',
  },
  {
    id: 'survey-003',
    initiativeId: 'init-004',
    title: 'Power BI – NPS de Treinamento',
    questions: [
      {
        id: 'q1',
        text: 'Em uma escala de 0 a 10, o quanto você recomendaria o treinamento de Power BI?',
        type: 'nps',
        adkarStage: 'knowledge',
      },
    ],
    targetDepartments: ['TI', 'RH', 'Financeiro', 'Operações'],
    responseRate: 89,
    createdAt: '2026-05-25T08:00:00Z',
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, userId: 'u1', userName: 'Ana Souza', department: 'TI', points: 4850, badges: 6, trend: 'up' },
  { rank: 2, userId: 'u2', userName: 'Carlos Lima', department: 'RH', points: 4200, badges: 5, trend: 'stable' },
  { rank: 3, userId: 'u3', userName: 'Maria Ferreira', department: 'Vendas', points: 3900, badges: 4, trend: 'up' },
  { rank: 4, userId: 'u4', userName: 'Pedro Costa', department: 'Operações', points: 3400, badges: 3, trend: 'down' },
  { rank: 5, userId: 'u5', userName: 'Lúcia Mendes', department: 'TI', points: 3100, badges: 4, trend: 'up' },
  { rank: 6, userId: 'u6', userName: 'João Alves', department: 'Financeiro', points: 2800, badges: 2, trend: 'stable' },
  { rank: 7, userId: 'u7', userName: 'Sofia Rocha', department: 'Marketing', points: 2500, badges: 3, trend: 'up' },
  { rank: 8, userId: 'u8', userName: 'Rafael Dias', department: 'Compras', points: 2200, badges: 2, trend: 'down' },
];

export const MOCK_NUDGES: Nudge[] = [
  {
    id: 'n1',
    initiativeId: 'init-001',
    recipientId: 'u1',
    channel: 'slack',
    subject: 'Você está quase lá! 🚀',
    body: 'Oi Ana! Seu time está a apenas 8% de atingir a meta de adoção do M365. Aqui estão 3 dicas rápidas para acelerar: (1) Migre seu calendário hoje, (2) Faça sua próxima reunião pelo Teams, (3) Salve um arquivo no OneDrive.',
    adkarStage: 'ability',
    status: 'clicked',
    scheduledAt: '2026-05-28T09:00:00Z',
    sentAt: '2026-05-28T09:01:00Z',
    openedAt: '2026-05-28T09:15:00Z',
  },
  {
    id: 'n2',
    initiativeId: 'init-002',
    recipientId: 'u3',
    channel: 'email',
    subject: 'Por que o Salesforce vai mudar sua rotina',
    body: 'Oi Maria! Sabemos que a migração para o Salesforce parece complexa, mas times que já completaram essa transição relatam 35% menos tempo em atualização de oportunidades. Preparamos um vídeo de 5 minutos especialmente para você.',
    adkarStage: 'awareness',
    status: 'opened',
    scheduledAt: '2026-05-27T10:00:00Z',
    sentAt: '2026-05-27T10:00:00Z',
    openedAt: '2026-05-27T14:30:00Z',
  },
  {
    id: 'n3',
    initiativeId: 'init-003',
    recipientId: 'u6',
    channel: 'teams',
    subject: 'Treinamento SAP disponível',
    body: 'João, seu módulo de treinamento do SAP Fiori está disponível. Duração: 45 min. Colaboradores que completaram o treinamento têm 60% menos erros na entrada de dados.',
    adkarStage: 'knowledge',
    status: 'sent',
    scheduledAt: '2026-05-29T08:00:00Z',
    sentAt: '2026-05-29T08:00:00Z',
  },
  {
    id: 'n4',
    initiativeId: 'init-004',
    recipientId: 'u4',
    channel: 'in_app',
    subject: 'Missão desbloqueada: Primeiro Dashboard',
    body: 'Pedro, você acabou de desbloquear a missão "Primeiro Dashboard"! Crie seu primeiro relatório no Power BI e ganhe 200 pontos. Seu time está dependendo de você!',
    adkarStage: 'reinforcement',
    status: 'pending',
    scheduledAt: '2026-05-30T09:00:00Z',
  },
];
